// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZijPAEBVs96HFl3hLPOHPzq7VgplDzTM',
    appId: '1:244740408679:web:f467fd5aa670877062dbc2',
    messagingSenderId: '244740408679',
    projectId: 'nzaker-4e5d5',
    authDomain: 'nzaker-4e5d5.firebaseapp.com',
    storageBucket: 'nzaker-4e5d5.appspot.com',
    measurementId: 'G-MTBTR6PSQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjuCKWaRO9qm0SYP4_0Hjbj5GUqV-dZ5k',
    appId: '1:244740408679:android:e6ea014b39659dc962dbc2',
    messagingSenderId: '244740408679',
    projectId: 'nzaker-4e5d5',
    storageBucket: 'nzaker-4e5d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo9TS8cVeC5igpmCA-F1lh4bnu05-nrKc',
    appId: '1:244740408679:ios:6bade67db0cf099262dbc2',
    messagingSenderId: '244740408679',
    projectId: 'nzaker-4e5d5',
    storageBucket: 'nzaker-4e5d5.appspot.com',
    iosBundleId: 'com.example.nzaker',
  );
}
